# Packfire Framework for PHP
#
# Options subpackage
#
# this file provides configuration for Travis Continuous Integration
# See Packfire's Options on TravisCI at http://travis-ci.org/packfire/options

language: php
php:
  - 5.3
  - 5.3.3
  - 5.4
before_script:
  - composer install
script: phpunit -c phpunit.xml.dist
after_script:
  - "wget --quiet https://github.com/downloads/packfire/pdc/pdc.phar && php pdc.phar src"