<?php
/**
 * Packfire Options
 * By Sam-Mauris Yong
 * 
 * Released open source under New BSD 3-Clause License.
 * Copyright (c) 2012, Sam-Mauris Yong Shan Xian <sam@mauris.sg>
 * All rights reserved.
 */

namespace Packfire\Options;

/**
 * Test class for Option.
 * Generated by PHPUnit on 2012-10-19 at 04:26:09.
 */
class OptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Option
     */
    protected $object;

    private $check;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Option('!test|t=', array($this, 'setFlag'), 'Some help text');
    }

    public function setFlag($data)
    {
        $this->check = $data;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Packfire\Options\Option::index
     */
    public function testIndex()
    {
        $this->assertEquals('!test|t=', $this->object->index());
    }
    
    /**
     * @covers Packfire\Options\Option::names
     */
    public function testNames()
    {
        $this->assertEquals(array('test', 't'), $this->object->names());
    }

    /**
     * @covers Packfire\Options\Option::required
     */
    public function testRequired()
    {
        $this->assertTrue($this->object->required());
    }

    /**
     * @covers Packfire\Options\Option::hasValue
     */
    public function testHasValue()
    {
        $this->assertTrue($this->object->hasValue());
    }

    public function testMatchName()
    {
        $this->assertTrue($this->object->matchName('test'));
        $this->assertTrue($this->object->matchName('t'));
        $this->assertFalse($this->object->matchName('alpha'));
    }

    public function testHelp()
    {
        $this->assertEquals('Some help text', $this->object->help());
    }

    public function testParse()
    {
        $this->object->parse(5);
        $this->assertEquals(5, $this->check);
    }
}
